networks:
  nginx_default:
    external: true

services:
  duckument-db:
    container_name: duckument-db
    image: mongo:8.0
    volumes:
      - data:/data/db
    ports:
      - '27017:27017'
    networks:
      - nginx_default

  duckument:
    container_name: duckument
    build: .
    ports:
      - '3000:3000'
      - '5173:5173'
    depends_on:
      - duckument-db
    networks:
      - nginx_default

volumes:
  data: